# Generated by Django 5.1 on 2024-08-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_service_contact_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Booking',
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.service'),
        ),
    ]
