# Generated by Django 5.1 on 2024-08-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_rename_contact_booking_service_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parent',
        ),
    ]
