# Generated by Django 5.1 on 2024-08-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
