# Generated by Django 5.1 on 2024-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='logo.png', null=True, upload_to='values')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100, verbose_name='Description')),
                ('sort', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
