# Generated by Django 5.1 on 2024-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100, verbose_name='Description')),
                ('sort', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Why Us',
            },
        ),
        migrations.AlterField(
            model_name='value',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='values'),
        ),
    ]
