# Generated by Django 5.1 on 2024-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_social_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='url',
            new_name='link',
        ),
    ]
