# Generated by Django 5.0 on 2024-08-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort']},
        ),
    ]
