# Generated by Django 5.0 on 2024-08-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_banner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
