# Generated by Django 5.1 on 2024-08-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
