# Generated by Django 5.1 on 2024-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
