# Generated by Django 5.1 on 2024-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_service_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sort',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
