# Generated by Django 5.1 on 2024-09-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='services'),
        ),
    ]
