# Generated by Django 5.1 on 2024-09-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sender',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cc_myself',
        ),
    ]
