# Generated by Django 5.1 on 2024-09-19 23:21

import page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_rename_sender_booking_email_remove_booking_cc_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=page.models.Value.content_file_name),
        ),
    ]
