# Generated by Django 5.1 on 2024-09-19 23:23

import page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_value_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=page.models.Service.content_file_name),
        ),
    ]
